.\" kkterminalqt
.TH "kkterminalqt" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
kkterminalqt \- manual page for kkterminalqt 0.0.0
.SH "SYNOPSIS"
.B kkterminalqt
.SH "DESCRIPTION"
A GUI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
kkterminalqt
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
